use super::Instruction;

pub const PREFIXED_INSTRUCTIONS: [Instruction; 256] = [
    Instruction {
        mnemonic: "RLC",
        bytes: 2,
        cycles: 8,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "RLC",
        bytes: 2,
        cycles: 8,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "RLC",
        bytes: 2,
        cycles: 8,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "RLC",
        bytes: 2,
        cycles: 8,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "RLC",
        bytes: 2,
        cycles: 8,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "RLC",
        bytes: 2,
        cycles: 8,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "RLC",
        bytes: 2,
        cycles: 16,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "RLC",
        bytes: 2,
        cycles: 8,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "RRC",
        bytes: 2,
        cycles: 8,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "RRC",
        bytes: 2,
        cycles: 8,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "RRC",
        bytes: 2,
        cycles: 8,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "RRC",
        bytes: 2,
        cycles: 8,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "RRC",
        bytes: 2,
        cycles: 8,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "RRC",
        bytes: 2,
        cycles: 8,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "RRC",
        bytes: 2,
        cycles: 16,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "RRC",
        bytes: 2,
        cycles: 8,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "RL",
        bytes: 2,
        cycles: 8,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "RL",
        bytes: 2,
        cycles: 8,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "RL",
        bytes: 2,
        cycles: 8,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "RL",
        bytes: 2,
        cycles: 8,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "RL",
        bytes: 2,
        cycles: 8,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "RL",
        bytes: 2,
        cycles: 8,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "RL",
        bytes: 2,
        cycles: 16,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "RL",
        bytes: 2,
        cycles: 8,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "RR",
        bytes: 2,
        cycles: 8,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "RR",
        bytes: 2,
        cycles: 8,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "RR",
        bytes: 2,
        cycles: 8,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "RR",
        bytes: 2,
        cycles: 8,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "RR",
        bytes: 2,
        cycles: 8,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "RR",
        bytes: 2,
        cycles: 8,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "RR",
        bytes: 2,
        cycles: 16,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "RR",
        bytes: 2,
        cycles: 8,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "SLA",
        bytes: 2,
        cycles: 8,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "SLA",
        bytes: 2,
        cycles: 8,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "SLA",
        bytes: 2,
        cycles: 8,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "SLA",
        bytes: 2,
        cycles: 8,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "SLA",
        bytes: 2,
        cycles: 8,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "SLA",
        bytes: 2,
        cycles: 8,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "SLA",
        bytes: 2,
        cycles: 16,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "SLA",
        bytes: 2,
        cycles: 8,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "SRA",
        bytes: 2,
        cycles: 8,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "SRA",
        bytes: 2,
        cycles: 8,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "SRA",
        bytes: 2,
        cycles: 8,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "SRA",
        bytes: 2,
        cycles: 8,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "SRA",
        bytes: 2,
        cycles: 8,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "SRA",
        bytes: 2,
        cycles: 8,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "SRA",
        bytes: 2,
        cycles: 16,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "SRA",
        bytes: 2,
        cycles: 8,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "SWAP",
        bytes: 2,
        cycles: 8,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "SWAP",
        bytes: 2,
        cycles: 8,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "SWAP",
        bytes: 2,
        cycles: 8,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "SWAP",
        bytes: 2,
        cycles: 8,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "SWAP",
        bytes: 2,
        cycles: 8,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "SWAP",
        bytes: 2,
        cycles: 8,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "SWAP",
        bytes: 2,
        cycles: 16,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "SWAP",
        bytes: 2,
        cycles: 8,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "SRL",
        bytes: 2,
        cycles: 8,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "SRL",
        bytes: 2,
        cycles: 8,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "SRL",
        bytes: 2,
        cycles: 8,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "SRL",
        bytes: 2,
        cycles: 8,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "SRL",
        bytes: 2,
        cycles: 8,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "SRL",
        bytes: 2,
        cycles: 8,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "SRL",
        bytes: 2,
        cycles: 16,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "SRL",
        bytes: 2,
        cycles: 8,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["0","B"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["0","C"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["0","D"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["0","E"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["0","H"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["0","L"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 12,
        operands: ["0","HL"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["0","A"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["1","B"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["1","C"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["1","D"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["1","E"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["1","H"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["1","L"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 12,
        operands: ["1","HL"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["1","A"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["2","B"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["2","C"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["2","D"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["2","E"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["2","H"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["2","L"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 12,
        operands: ["2","HL"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["2","A"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["3","B"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["3","C"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["3","D"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["3","E"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["3","H"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["3","L"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 12,
        operands: ["3","HL"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["3","A"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["4","B"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["4","C"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["4","D"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["4","E"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["4","H"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["4","L"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 12,
        operands: ["4","HL"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["4","A"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["5","B"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["5","C"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["5","D"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["5","E"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["5","H"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["5","L"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 12,
        operands: ["5","HL"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["5","A"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["6","B"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["6","C"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["6","D"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["6","E"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["6","H"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["6","L"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 12,
        operands: ["6","HL"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["6","A"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["7","B"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["7","C"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["7","D"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["7","E"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["7","H"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["7","L"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 12,
        operands: ["7","HL"],
    },
    Instruction {
        mnemonic: "BIT",
        bytes: 2,
        cycles: 8,
        operands: ["7","A"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["0","B"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["0","C"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["0","D"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["0","E"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["0","H"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["0","L"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 16,
        operands: ["0","HL"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["0","A"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["1","B"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["1","C"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["1","D"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["1","E"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["1","H"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["1","L"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 16,
        operands: ["1","HL"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["1","A"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["2","B"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["2","C"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["2","D"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["2","E"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["2","H"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["2","L"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 16,
        operands: ["2","HL"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["2","A"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["3","B"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["3","C"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["3","D"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["3","E"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["3","H"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["3","L"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 16,
        operands: ["3","HL"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["3","A"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["4","B"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["4","C"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["4","D"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["4","E"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["4","H"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["4","L"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 16,
        operands: ["4","HL"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["4","A"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["5","B"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["5","C"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["5","D"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["5","E"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["5","H"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["5","L"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 16,
        operands: ["5","HL"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["5","A"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["6","B"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["6","C"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["6","D"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["6","E"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["6","H"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["6","L"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 16,
        operands: ["6","HL"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["6","A"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["7","B"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["7","C"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["7","D"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["7","E"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["7","H"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["7","L"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 16,
        operands: ["7","HL"],
    },
    Instruction {
        mnemonic: "RES",
        bytes: 2,
        cycles: 8,
        operands: ["7","A"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["0","B"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["0","C"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["0","D"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["0","E"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["0","H"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["0","L"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 16,
        operands: ["0","HL"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["0","A"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["1","B"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["1","C"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["1","D"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["1","E"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["1","H"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["1","L"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 16,
        operands: ["1","HL"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["1","A"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["2","B"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["2","C"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["2","D"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["2","E"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["2","H"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["2","L"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 16,
        operands: ["2","HL"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["2","A"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["3","B"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["3","C"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["3","D"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["3","E"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["3","H"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["3","L"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 16,
        operands: ["3","HL"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["3","A"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["4","B"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["4","C"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["4","D"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["4","E"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["4","H"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["4","L"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 16,
        operands: ["4","HL"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["4","A"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["5","B"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["5","C"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["5","D"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["5","E"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["5","H"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["5","L"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 16,
        operands: ["5","HL"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["5","A"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["6","B"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["6","C"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["6","D"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["6","E"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["6","H"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["6","L"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 16,
        operands: ["6","HL"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["6","A"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["7","B"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["7","C"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["7","D"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["7","E"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["7","H"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["7","L"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 16,
        operands: ["7","HL"],
    },
    Instruction {
        mnemonic: "SET",
        bytes: 2,
        cycles: 8,
        operands: ["7","A"],
    },
];