use super::Instruction;

pub const UNPREFIXED_INSTRUCTIONS: [Instruction; 256] = [
    Instruction {
        mnemonic: "NOP",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 3,
        cycles: 12,
        operands: ["BC","n16"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["BC","A"],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 8,
        operands: ["BC",""],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 4,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 4,
        operands: ["B",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 2,
        cycles: 8,
        operands: ["B","n8"],
    },
    Instruction {
        mnemonic: "RLCA",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 3,
        cycles: 20,
        operands: ["a16","SP"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","BC"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["A","BC"],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 8,
        operands: ["BC",""],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 4,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 4,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 2,
        cycles: 8,
        operands: ["C","n8"],
    },
    Instruction {
        mnemonic: "RRCA",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "STOP",
        bytes: 2,
        cycles: 4,
        operands: ["n8",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 3,
        cycles: 12,
        operands: ["DE","n16"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["DE","A"],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 8,
        operands: ["DE",""],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 4,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 4,
        operands: ["D",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 2,
        cycles: 8,
        operands: ["D","n8"],
    },
    Instruction {
        mnemonic: "RLA",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "JR",
        bytes: 2,
        cycles: 12,
        operands: ["e8",""],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","DE"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["A","DE"],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 8,
        operands: ["DE",""],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 4,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 4,
        operands: ["E",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 2,
        cycles: 8,
        operands: ["E","n8"],
    },
    Instruction {
        mnemonic: "RRA",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "JR",
        bytes: 2,
        cycles: 12,
        operands: ["NZ","e8"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 3,
        cycles: 12,
        operands: ["HL","n16"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","A"],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 8,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 4,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 4,
        operands: ["H",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 2,
        cycles: 8,
        operands: ["H","n8"],
    },
    Instruction {
        mnemonic: "DAA",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "JR",
        bytes: 2,
        cycles: 12,
        operands: ["Z","e8"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","HL"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 8,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 4,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 4,
        operands: ["L",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 2,
        cycles: 8,
        operands: ["L","n8"],
    },
    Instruction {
        mnemonic: "CPL",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "JR",
        bytes: 2,
        cycles: 12,
        operands: ["NC","e8"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 3,
        cycles: 12,
        operands: ["SP","n16"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","A"],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 8,
        operands: ["SP",""],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 12,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 12,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 2,
        cycles: 12,
        operands: ["HL","n8"],
    },
    Instruction {
        mnemonic: "SCF",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "JR",
        bytes: 2,
        cycles: 12,
        operands: ["C","e8"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","SP"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 8,
        operands: ["SP",""],
    },
    Instruction {
        mnemonic: "INC",
        bytes: 1,
        cycles: 4,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "DEC",
        bytes: 1,
        cycles: 4,
        operands: ["A",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 2,
        cycles: 8,
        operands: ["A","n8"],
    },
    Instruction {
        mnemonic: "CCF",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["B","B"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["B","C"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["B","D"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["B","E"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["B","H"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["B","L"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["B","HL"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["B","A"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["C","B"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["C","C"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["C","D"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["C","E"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["C","H"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["C","L"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["C","HL"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["C","A"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["D","B"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["D","C"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["D","D"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["D","E"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["D","H"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["D","L"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["D","HL"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["D","A"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["E","B"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["E","C"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["E","D"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["E","E"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["E","H"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["E","L"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["E","HL"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["E","A"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["H","B"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["H","C"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["H","D"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["H","E"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["H","H"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["H","L"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["H","HL"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["H","A"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["L","B"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["L","C"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["L","D"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["L","E"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["L","H"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["L","L"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["L","HL"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["L","A"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","B"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","C"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","D"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","E"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","H"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","L"],
    },
    Instruction {
        mnemonic: "HALT",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["HL","A"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["A","B"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["A","D"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["A","E"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["A","H"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["A","L"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 4,
        operands: ["A","A"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 4,
        operands: ["A","B"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 4,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 4,
        operands: ["A","D"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 4,
        operands: ["A","E"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 4,
        operands: ["A","H"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 4,
        operands: ["A","L"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 1,
        cycles: 4,
        operands: ["A","A"],
    },
    Instruction {
        mnemonic: "ADC",
        bytes: 1,
        cycles: 4,
        operands: ["A","B"],
    },
    Instruction {
        mnemonic: "ADC",
        bytes: 1,
        cycles: 4,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "ADC",
        bytes: 1,
        cycles: 4,
        operands: ["A","D"],
    },
    Instruction {
        mnemonic: "ADC",
        bytes: 1,
        cycles: 4,
        operands: ["A","E"],
    },
    Instruction {
        mnemonic: "ADC",
        bytes: 1,
        cycles: 4,
        operands: ["A","H"],
    },
    Instruction {
        mnemonic: "ADC",
        bytes: 1,
        cycles: 4,
        operands: ["A","L"],
    },
    Instruction {
        mnemonic: "ADC",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "ADC",
        bytes: 1,
        cycles: 4,
        operands: ["A","A"],
    },
    Instruction {
        mnemonic: "SUB",
        bytes: 1,
        cycles: 4,
        operands: ["A","B"],
    },
    Instruction {
        mnemonic: "SUB",
        bytes: 1,
        cycles: 4,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "SUB",
        bytes: 1,
        cycles: 4,
        operands: ["A","D"],
    },
    Instruction {
        mnemonic: "SUB",
        bytes: 1,
        cycles: 4,
        operands: ["A","E"],
    },
    Instruction {
        mnemonic: "SUB",
        bytes: 1,
        cycles: 4,
        operands: ["A","H"],
    },
    Instruction {
        mnemonic: "SUB",
        bytes: 1,
        cycles: 4,
        operands: ["A","L"],
    },
    Instruction {
        mnemonic: "SUB",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "SUB",
        bytes: 1,
        cycles: 4,
        operands: ["A","A"],
    },
    Instruction {
        mnemonic: "SBC",
        bytes: 1,
        cycles: 4,
        operands: ["A","B"],
    },
    Instruction {
        mnemonic: "SBC",
        bytes: 1,
        cycles: 4,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "SBC",
        bytes: 1,
        cycles: 4,
        operands: ["A","D"],
    },
    Instruction {
        mnemonic: "SBC",
        bytes: 1,
        cycles: 4,
        operands: ["A","E"],
    },
    Instruction {
        mnemonic: "SBC",
        bytes: 1,
        cycles: 4,
        operands: ["A","H"],
    },
    Instruction {
        mnemonic: "SBC",
        bytes: 1,
        cycles: 4,
        operands: ["A","L"],
    },
    Instruction {
        mnemonic: "SBC",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "SBC",
        bytes: 1,
        cycles: 4,
        operands: ["A","A"],
    },
    Instruction {
        mnemonic: "AND",
        bytes: 1,
        cycles: 4,
        operands: ["A","B"],
    },
    Instruction {
        mnemonic: "AND",
        bytes: 1,
        cycles: 4,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "AND",
        bytes: 1,
        cycles: 4,
        operands: ["A","D"],
    },
    Instruction {
        mnemonic: "AND",
        bytes: 1,
        cycles: 4,
        operands: ["A","E"],
    },
    Instruction {
        mnemonic: "AND",
        bytes: 1,
        cycles: 4,
        operands: ["A","H"],
    },
    Instruction {
        mnemonic: "AND",
        bytes: 1,
        cycles: 4,
        operands: ["A","L"],
    },
    Instruction {
        mnemonic: "AND",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "AND",
        bytes: 1,
        cycles: 4,
        operands: ["A","A"],
    },
    Instruction {
        mnemonic: "XOR",
        bytes: 1,
        cycles: 4,
        operands: ["A","B"],
    },
    Instruction {
        mnemonic: "XOR",
        bytes: 1,
        cycles: 4,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "XOR",
        bytes: 1,
        cycles: 4,
        operands: ["A","D"],
    },
    Instruction {
        mnemonic: "XOR",
        bytes: 1,
        cycles: 4,
        operands: ["A","E"],
    },
    Instruction {
        mnemonic: "XOR",
        bytes: 1,
        cycles: 4,
        operands: ["A","H"],
    },
    Instruction {
        mnemonic: "XOR",
        bytes: 1,
        cycles: 4,
        operands: ["A","L"],
    },
    Instruction {
        mnemonic: "XOR",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "XOR",
        bytes: 1,
        cycles: 4,
        operands: ["A","A"],
    },
    Instruction {
        mnemonic: "OR",
        bytes: 1,
        cycles: 4,
        operands: ["A","B"],
    },
    Instruction {
        mnemonic: "OR",
        bytes: 1,
        cycles: 4,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "OR",
        bytes: 1,
        cycles: 4,
        operands: ["A","D"],
    },
    Instruction {
        mnemonic: "OR",
        bytes: 1,
        cycles: 4,
        operands: ["A","E"],
    },
    Instruction {
        mnemonic: "OR",
        bytes: 1,
        cycles: 4,
        operands: ["A","H"],
    },
    Instruction {
        mnemonic: "OR",
        bytes: 1,
        cycles: 4,
        operands: ["A","L"],
    },
    Instruction {
        mnemonic: "OR",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "OR",
        bytes: 1,
        cycles: 4,
        operands: ["A","A"],
    },
    Instruction {
        mnemonic: "CP",
        bytes: 1,
        cycles: 4,
        operands: ["A","B"],
    },
    Instruction {
        mnemonic: "CP",
        bytes: 1,
        cycles: 4,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "CP",
        bytes: 1,
        cycles: 4,
        operands: ["A","D"],
    },
    Instruction {
        mnemonic: "CP",
        bytes: 1,
        cycles: 4,
        operands: ["A","E"],
    },
    Instruction {
        mnemonic: "CP",
        bytes: 1,
        cycles: 4,
        operands: ["A","H"],
    },
    Instruction {
        mnemonic: "CP",
        bytes: 1,
        cycles: 4,
        operands: ["A","L"],
    },
    Instruction {
        mnemonic: "CP",
        bytes: 1,
        cycles: 8,
        operands: ["A","HL"],
    },
    Instruction {
        mnemonic: "CP",
        bytes: 1,
        cycles: 4,
        operands: ["A","A"],
    },
    Instruction {
        mnemonic: "RET",
        bytes: 1,
        cycles: 20,
        operands: ["NZ",""],
    },
    Instruction {
        mnemonic: "POP",
        bytes: 1,
        cycles: 12,
        operands: ["BC",""],
    },
    Instruction {
        mnemonic: "JP",
        bytes: 3,
        cycles: 16,
        operands: ["NZ","a16"],
    },
    Instruction {
        mnemonic: "JP",
        bytes: 3,
        cycles: 16,
        operands: ["a16",""],
    },
    Instruction {
        mnemonic: "CALL",
        bytes: 3,
        cycles: 24,
        operands: ["NZ","a16"],
    },
    Instruction {
        mnemonic: "PUSH",
        bytes: 1,
        cycles: 16,
        operands: ["BC",""],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 2,
        cycles: 8,
        operands: ["A","n8"],
    },
    Instruction {
        mnemonic: "RST",
        bytes: 1,
        cycles: 16,
        operands: ["$00",""],
    },
    Instruction {
        mnemonic: "RET",
        bytes: 1,
        cycles: 20,
        operands: ["Z",""],
    },
    Instruction {
        mnemonic: "RET",
        bytes: 1,
        cycles: 16,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "JP",
        bytes: 3,
        cycles: 16,
        operands: ["Z","a16"],
    },
    Instruction {
        mnemonic: "PREFIX",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "CALL",
        bytes: 3,
        cycles: 24,
        operands: ["Z","a16"],
    },
    Instruction {
        mnemonic: "CALL",
        bytes: 3,
        cycles: 24,
        operands: ["a16",""],
    },
    Instruction {
        mnemonic: "ADC",
        bytes: 2,
        cycles: 8,
        operands: ["A","n8"],
    },
    Instruction {
        mnemonic: "RST",
        bytes: 1,
        cycles: 16,
        operands: ["$08",""],
    },
    Instruction {
        mnemonic: "RET",
        bytes: 1,
        cycles: 20,
        operands: ["NC",""],
    },
    Instruction {
        mnemonic: "POP",
        bytes: 1,
        cycles: 12,
        operands: ["DE",""],
    },
    Instruction {
        mnemonic: "JP",
        bytes: 3,
        cycles: 16,
        operands: ["NC","a16"],
    },
    Instruction {
        mnemonic: "ILLEGAL_D3",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "CALL",
        bytes: 3,
        cycles: 24,
        operands: ["NC","a16"],
    },
    Instruction {
        mnemonic: "PUSH",
        bytes: 1,
        cycles: 16,
        operands: ["DE",""],
    },
    Instruction {
        mnemonic: "SUB",
        bytes: 2,
        cycles: 8,
        operands: ["A","n8"],
    },
    Instruction {
        mnemonic: "RST",
        bytes: 1,
        cycles: 16,
        operands: ["$10",""],
    },
    Instruction {
        mnemonic: "RET",
        bytes: 1,
        cycles: 20,
        operands: ["C",""],
    },
    Instruction {
        mnemonic: "RETI",
        bytes: 1,
        cycles: 16,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "JP",
        bytes: 3,
        cycles: 16,
        operands: ["C","a16"],
    },
    Instruction {
        mnemonic: "ILLEGAL_DB",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "CALL",
        bytes: 3,
        cycles: 24,
        operands: ["C","a16"],
    },
    Instruction {
        mnemonic: "ILLEGAL_DD",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "SBC",
        bytes: 2,
        cycles: 8,
        operands: ["A","n8"],
    },
    Instruction {
        mnemonic: "RST",
        bytes: 1,
        cycles: 16,
        operands: ["$18",""],
    },
    Instruction {
        mnemonic: "LDH",
        bytes: 2,
        cycles: 12,
        operands: ["a8","A"],
    },
    Instruction {
        mnemonic: "POP",
        bytes: 1,
        cycles: 12,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "LDH",
        bytes: 1,
        cycles: 8,
        operands: ["C","A"],
    },
    Instruction {
        mnemonic: "ILLEGAL_E3",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "ILLEGAL_E4",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "PUSH",
        bytes: 1,
        cycles: 16,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "AND",
        bytes: 2,
        cycles: 8,
        operands: ["A","n8"],
    },
    Instruction {
        mnemonic: "RST",
        bytes: 1,
        cycles: 16,
        operands: ["$20",""],
    },
    Instruction {
        mnemonic: "ADD",
        bytes: 2,
        cycles: 16,
        operands: ["SP","e8"],
    },
    Instruction {
        mnemonic: "JP",
        bytes: 1,
        cycles: 4,
        operands: ["HL",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 3,
        cycles: 16,
        operands: ["a16","A"],
    },
    Instruction {
        mnemonic: "ILLEGAL_EB",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "ILLEGAL_EC",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "ILLEGAL_ED",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "XOR",
        bytes: 2,
        cycles: 8,
        operands: ["A","n8"],
    },
    Instruction {
        mnemonic: "RST",
        bytes: 1,
        cycles: 16,
        operands: ["$28",""],
    },
    Instruction {
        mnemonic: "LDH",
        bytes: 2,
        cycles: 12,
        operands: ["A","a8"],
    },
    Instruction {
        mnemonic: "POP",
        bytes: 1,
        cycles: 12,
        operands: ["AF",""],
    },
    Instruction {
        mnemonic: "LDH",
        bytes: 1,
        cycles: 8,
        operands: ["A","C"],
    },
    Instruction {
        mnemonic: "DI",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "ILLEGAL_F4",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "PUSH",
        bytes: 1,
        cycles: 16,
        operands: ["AF",""],
    },
    Instruction {
        mnemonic: "OR",
        bytes: 2,
        cycles: 8,
        operands: ["A","n8"],
    },
    Instruction {
        mnemonic: "RST",
        bytes: 1,
        cycles: 16,
        operands: ["$30",""],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 2,
        cycles: 12,
        operands: ["HL","SP"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 1,
        cycles: 8,
        operands: ["SP","HL"],
    },
    Instruction {
        mnemonic: "LD",
        bytes: 3,
        cycles: 16,
        operands: ["A","a16"],
    },
    Instruction {
        mnemonic: "EI",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "ILLEGAL_FC",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "ILLEGAL_FD",
        bytes: 1,
        cycles: 4,
        operands: ["",""],
    },
    Instruction {
        mnemonic: "CP",
        bytes: 2,
        cycles: 8,
        operands: ["A","n8"],
    },
    Instruction {
        mnemonic: "RST",
        bytes: 1,
        cycles: 16,
        operands: ["$38",""],
    },
];